# biobert_biolarkgsc.sub — submits the BioBERT-MRC baseline job for BioLarkGSC
executable = /home/johnwu3/projects/rare_disease/workspace/condor/hpo/run_biobert_biolarkgsc.sh

Requirements = (Machine == "sunlab-c02.cs.illinois.edu")

universe       = vanilla
request_cpus   = 16
request_memory = 32GB
request_gpus   = 1

log    = /home/johnwu3/projects/rare_disease/workspace/logs/biolarkgsc/biobert_mrc/$(Cluster).$(Process).log
output = /home/johnwu3/projects/rare_disease/workspace/logs/biolarkgsc/biobert_mrc/$(Cluster).$(Process).out
error  = /home/johnwu3/projects/rare_disease/workspace/logs/biolarkgsc/biobert_mrc/$(Cluster).$(Process).err

queue
