# bioclinicalbert_ner_biolarkgsc.sub — submits the BioClinicalBERT NER baseline job for BioLarkGSC
executable = /home/johnwu3/projects/rare_disease/workspace/condor/hpo/run_bioclinicalbert_ner_biolarkgsc.sh

Requirements = (Machine == "sunlab-c02.cs.illinois.edu")

universe       = vanilla
request_cpus   = 16
request_memory = 32GB
request_gpus   = 1

log    = /home/johnwu3/projects/rare_disease/workspace/logs/biolarkgsc/bioclinicalbert_ner/$(Cluster).$(Process).log
output = /home/johnwu3/projects/rare_disease/workspace/logs/biolarkgsc/bioclinicalbert_ner/$(Cluster).$(Process).out
error  = /home/johnwu3/projects/rare_disease/workspace/logs/biolarkgsc/bioclinicalbert_ner/$(Cluster).$(Process).err

queue
