# dictionary_hpo_csc.sub — submits one Dictionary HPO CSC baseline job
executable = /home/johnwu3/projects/rare_disease/workspace/condor/hpo/run_dictionary_hpo_csc.sh

Requirements = (Machine == "sunlab-c01.cs.illinois.edu")

universe       = vanilla
request_cpus   = 4
request_memory = 16GB
request_gpus   = 0

log    = /home/johnwu3/projects/rare_disease/workspace/logs/csc/dictionary_hpo/$(Cluster).$(Process).log
output = /home/johnwu3/projects/rare_disease/workspace/logs/csc/dictionary_hpo/$(Cluster).$(Process).out
error  = /home/johnwu3/projects/rare_disease/workspace/logs/csc/dictionary_hpo/$(Cluster).$(Process).err

queue
