# dict_rdd.sub — submits the dictionary baseline job for RDD
executable = /home/johnwu3/projects/rare_disease/workspace/condor/rare_disease/run_dict_rdd.sh

Requirements = (Machine == "sunlab-c02.cs.illinois.edu")

universe       = vanilla
request_cpus   = 16
request_memory = 32GB
request_gpus   = 1

log    = /home/johnwu3/projects/rare_disease/workspace/logs/rdd/dict/$(Cluster).$(Process).log
output = /home/johnwu3/projects/rare_disease/workspace/logs/rdd/dict/$(Cluster).$(Process).out
error  = /home/johnwu3/projects/rare_disease/workspace/logs/rdd/dict/$(Cluster).$(Process).err

queue
