# dict_mimic3_rd_mining.sub — submits the dictionary baseline job for MIMIC-III rare-disease mining (code-eval)
executable = /home/johnwu3/projects/rare_disease/workspace/condor/rare_disease/run_dict_mimic3_rd_mining.sh

Requirements = (Machine == "sunlab-c02.cs.illinois.edu")

universe       = vanilla
request_cpus   = 16
request_memory = 32GB
request_gpus   = 1

log    = /home/johnwu3/projects/rare_disease/workspace/logs/mimic3_rd_mining/dict/$(Cluster).$(Process).log
output = /home/johnwu3/projects/rare_disease/workspace/logs/mimic3_rd_mining/dict/$(Cluster).$(Process).out
error  = /home/johnwu3/projects/rare_disease/workspace/logs/mimic3_rd_mining/dict/$(Cluster).$(Process).err

queue
