# i2b2_raredis.sub — Stanza i2b2 NER baseline on RareDis
executable = /home/johnwu3/projects/rare_disease/workspace/condor/rare_disease/run_i2b2_raredis.sh

Requirements = (Machine == "sunlab-c02.cs.illinois.edu")

universe       = vanilla
request_cpus   = 4
request_memory = 32GB
request_gpus   = 1

log    = /home/johnwu3/projects/rare_disease/workspace/logs/raredis/i2b2/$(Cluster).$(Process).log
output = /home/johnwu3/projects/rare_disease/workspace/logs/raredis/i2b2/$(Cluster).$(Process).out
error  = /home/johnwu3/projects/rare_disease/workspace/logs/raredis/i2b2/$(Cluster).$(Process).err

queue
