# i2b2_mimic3.sub — Stanza i2b2 rare-disease baseline on MIMIC-III
executable = /home/johnwu3/projects/rare_disease/workspace/condor/rare_disease/run_i2b2_mimic3.sh

Requirements = (Machine == "sunlab-c02.cs.illinois.edu")

universe       = vanilla
request_cpus   = 4
request_memory = 32GB
request_gpus   = 1

log    = /home/johnwu3/projects/rare_disease/workspace/logs/mimic3/i2b2_rd/$(Cluster).$(Process).log
output = /home/johnwu3/projects/rare_disease/workspace/logs/mimic3/i2b2_rd/$(Cluster).$(Process).out
error  = /home/johnwu3/projects/rare_disease/workspace/logs/mimic3/i2b2_rd/$(Cluster).$(Process).err

queue
