version: "1.0"
tables:
  texts:
    file_path: "texts.csv"
    patient_id: "id"
    timestamp: null
    attributes:
      - "split"
      - "text"

  annotations:
    file_path: "annotations.csv"
    patient_id: "id"
    timestamp: null
    attributes:
      - "ann_id"
      - "annotation_type"
      - "start"
      - "end"
      - "annotation"

  relations:
    file_path: "relations.csv"
    patient_id: "id"
    timestamp: null
    attributes:
      - "rel_id"
      - "relation_type"
      - "arg1"
      - "arg2"
